# Generated by Django 3.2.7 on 2021-09-13 17:44

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(blank=True, default='default-images/default.jpg', null=True, upload_to=posts.models.get_post_image_path),
        ),
    ]
