# Generated by Django 3.2.7 on 2021-11-09 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_profile_profile_image'), ('users', '0003_alter_profile_profile_image'), ('users', '0004_alter_profile_profile_image'), ('users', '0005_profile_privacy'), ('users', '0006_profile_follower_user'), ('users', '0007_remove_profile_follower_user'), ('users', '0008_userfollowing'), ('users', '0009_alter_userfollowing_unique_together')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, default='default-images/default.jpg', null=True, upload_to=users.models.get_user_image_path)),
                ('privacy', models.CharField(choices=[('PRIV', 'Private'), ('PUBL', 'Public')], default='PUBL', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'following_user')},
            },
        ),
    ]
