# Generated by Django 3.2.7 on 2021-09-13 17:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-images/default.jpg', null=True, upload_to=users.models.get_user_image_path),
        ),
    ]
