# Generated by Django 3.2.7 on 2021-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('PRIV', 'Private'), ('PUBL', 'Public')], default='PUBL', max_length=4),
        ),
    ]
