# Generated by Django 3.2.7 on 2021-10-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_follower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower_user',
        ),
    ]
