# Generated by Django 3.2.7 on 2021-11-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('comments', '0001_initial'), ('comments', '0002_alter_comment_post'), ('comments', '0003_alter_comment_id'), ('comments', '0004_alter_comment_post'), ('comments', '0005_alter_comment_post'), ('comments', '0006_alter_comment_post'), ('comments', '0007_alter_comment_post'), ('comments', '0008_alter_comment_post'), ('comments', '0009_alter_comment_text'), ('comments', '0010_alter_comment_text')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_alter_post_tags'),
        ('posts', '0003_alter_postphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
    ]
