# Generated by Django 3.2.7 on 2021-10-10 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
